#!/bin/sh

theme_name=$1
vim_config=$HOME/.config/nvim/lua
# p10k_config=$HOME/.p10k.zsh
alacritty_config=$HOME/.config/alacritty

configure_alacritty() {
  cat ${alacritty_config}/alacritty_${theme_name}.toml > ${alacritty_config}/alacritty.toml
}

configure_vim() {
  cat ${vim_config}/themes/${theme_name}_init.lua > ${vim_config}/theme.lua
}

# configure_p10k() {
#   sed -i "s/.*typeset -g POWERLEVEL9K_BACKGROUND=.*/  typeset -g POWERLEVEL9K_BACKGROUND=$1/" ${p10k_config}
# }

case $theme_name in
  rosepine_dawn)
    configure_alacritty
    configure_vim
    # configure_p10k "253"
    ;;
  tokyonight_moon)
    configure_alacritty
    configure_vim
    # configure_p10k "253"
    ;;
  *)
    echo "Theme not found"
    exit 1
    ;;
esac
