" colorscheme is generated by ~/.myconfig/colorscheme

" settings/colors_theme_[theme_name] part
set termguicolors
let g:sonokai_style = 'atlantis'
let g:sonokai_enable_italic = 1
let g:sonokai_disable_italic_comment = 0
let g:sonokai_diagnostic_text_highlight = 1
let g:sonokai_diagnostic_line_highlight = 1
let g:sonokai_diagnostic_virtual_text = 'colored'
colorscheme sonokai
let g:airline_theme = 'sonokai'

" ~/.vim/plugged/sonokai/colors/sonokai.vim
