" colorscheme is generated by ~/.myconfig/colorscheme

" settings/colors_theme_[theme_name] part
set termguicolors
let ayucolor='light'
colorscheme ayu

# updates
# ~/.vim/plugged/ayu-vim/colors/ayu.vim
" use alacritty bg color
" let s:palette.bg = {'light': "#FFFFFF",  'mirage': "#262626"}
