" colorscheme is generated by ~/.myconfig/colorscheme

" settings/colors_theme_[theme_name] part
set termguicolors
colorscheme one
set background=light
let g:airline_theme='one'

" ~/.vim/plugged/vim-one/colors/one.vim
